### ISSUE TITLE
Extracted microcode too short.

### ISSUE THREAD

**Issue by kernschmelze** [platomav/CPUMicrocodes#1]
Hello platomav, first let me say thank you very much for that great tool!

However, it has an issue. When I used it to extract a microcode, I realized that it is broken:

> # ./cpupdate -f /home/stefan/Downloads/cpu206C2_plat03_ver0000001D_2015-08-04_PRD_F7DC758B.bin
> File /home/stefan/Downloads/cpu206C2_plat03_ver0000001D_2015-08-04_PRD_F7DC758B.bin does not contain a valid header
> File /home/stefan/Downloads/cpu206C2_plat03_ver0000001D_2015-08-04_PRD_F7DC758B.bin is incomplete (too short)
> #
When I looked at the file, I noticed that it was a multiple of 1024 bytes. This suggested me that you forgot to add 48 bytes, which is the header size, to the blob size. This way my microcode updater found that the file is corrupt.

I verified this assumption with this:

> #include <stdio.h>
> #include <unistd.h>
> #include <fcntl.h>
> 
> char *blobf  = "Rom.bin";       // name of 2MB BIOS image
> char *ucodef = "06-2c-02-1d";   // name of microcode update file to be extracted
> #define MICROCODESIZE 9264
> char microcode[ MICROCODESIZE];
> int r;
> int offset = 0x77850;
> 
> int main()
> {
>   int blobfd, ucodefd;
>   
>   if ((r = ((blobfd = open( blobf, O_RDONLY, 0)) < 0))) {
>     printf( "Failed to open %s file\n", blobf);
>   }
>   if (!r && ((r = (lseek( blobfd, offset, 0) != offset)))) {
>     printf( "Failed to seek position %d in file %s\n", offset, blobf);
>   }
>   if (!r && (r = (read( blobfd, microcode, MICROCODESIZE) != MICROCODESIZE))) {
>     printf( "Failed to read %d bytes from offset %d in file %s\n", MICROCODESIZE, offset, blobf);
>   }
>   if (!r && (r = (close( blobfd)))) {
>     printf( "Failed to close file %s\n", blobf);
>   }
>   if (!r && (r = ((ucodefd = creat( ucodef, 0644)) < 0))) {
>     printf( "Failed to create microcode file %s\n", ucodef);
>   }
>   if (!r && (r = ((write( ucodefd, microcode, MICROCODESIZE)) != MICROCODESIZE))) {
>     printf( "Failed to write %d bytes microcode to file %s\n", MICROCODESIZE, ucodef);
>   }
>   if (!r && (r = (close( ucodefd)))) {
>     printf( "Failed to close file %s\n", ucodef);
>   }
>   return r;
> }
9264 is the 9x1024+48 bytes, 0x77850 is the offset displayed by MCE.
The resulting file was correct, size, checksum etc all were fine:

> # ./cpupdate -f /home/stefan/microcoding/06-2c-02-1d 
> Update file properties:
> Header version 1 (0x1)
> Revision 29 (0x1d)
> Date 08042015
> File is to be used for processors with these stats:
> ProcessorType:  00
> ExtFamily: 00  ExtModel: 02
> IntFamily: 06  IntModel: 0C  Stepping: 02
> -> Family: 06  Model:    2C
> Loader revision required to upload this microcode: 1 (0x1)
> Processor Flags 3 (0x00000003)
> Data size 9168 (0x23d0)
> Has no extended header.
> #

I think the problem will be easy to fix, just check if you need to add 48 bytes for the header.
See my cpupdate repo, it contains links to the relevant Intel documents.

You might want to use cpupdate -f option to check which files of your microcode library are complete and which ones are not, and need to be re-created.

Thank you again for your wonderful MCE tool!
Have a nice day!
Stefan

**Comment by platomav** [comment]
Hello Stefan,

Thank you for using MCE and the CPU Repositories. Isn't this supposed to be a MCE issue? If yes, this seems like the wrong repository.

Anyway, there shouldn't be any issue with MCE. It is not possible for it to detect a microcode if the header is not there in the first place. Also, among other health checks, it verifies from the Header its Size and Checksum (which covers the entire blob). So a missing header is not possible. For example, I checked the microcode you mentioned (cpu206C2_plat03_ver0000001D_2015-08-04_PRD_F7DC758B) and it is perfect. I suspect there is some sort of bug in your tool.

**Comment by kernschmelze** [comment]
I have to apologize, you are right.
It was an error in the check for data_size equaling zero I have missed when refactoring old spaghetti code I took over. I went over it a few times trying to figure out what was wrong, and missed it.
I think I must sleep more 8)
So this issue can be closed.

And thank you again for this great ucode library.

**Comment by platomav** [comment]
Yeap, that makes sense. Once again, thank you for using MCE. :)
