### ISSUE TITLE
PEP1.PDB (x3), PEP4.PDB (x6) microcodes

### ISSUE THREAD

**Issue by sladen** [platomav/CPUMicrocodes#10]
* http://files.mpoli.fi/hardware/MISC/OTHER/PPROUPD.ZIP

contains two further `.zip` files: `update20.zip` (contain `PEP1.PDB` from 1996) and `update32.zip` (containing `PEB4.PDB` from 1997).  These contain:

```
$ for pdb in *.PDB ; do echo $pdb ; hexdump -C $pdb | cut -c5-58 ; done | grep -E '(PDB|00  01 00 0)'
PEP1.PDB
0000  01 00 00 00 c5 00 00 00  95 19 25 01 16 06 00 00
0800  01 00 00 00 c5 00 00 00  96 19 05 01 12 06 00 00
1000  01 00 00 00 c5 00 00 00  95 19 25 01 17 06 00 00
PEP4.PDB
0000  01 00 00 00 c6 00 00 00  96 19 10 12 12 06 00 00
0800  01 00 00 00 c6 00 00 00  96 19 10 12 16 06 00 00
1000  01 00 00 00 c6 00 00 00  96 19 10 12 17 06 00 00
1800  01 00 00 00 d1 00 00 00  96 18 07 00 19 06 00 00
2000  01 00 00 00 13 00 00 00  96 19 27 08 30 06 00 00
2800  01 00 00 00 20 00 00 00  96 19 03 09 32 06 00 00
3000  01 00 00 00 32 00 00 00  96 19 12 12 33 06 00 00
```

Three of these likely have typos in the metadata… the two claiming to be from 1995-01-25 are more likely to be from 1996-01-26.  The one claiming to be from 1896-07-00 is more likely to be to from 1996-07-18, and quite possibly is _not_ stepping 0x619, but really 0x618 (based on the adjacent typo).

In addition:
* ftp://retronn.de/driver/Collections/2/IDE/TXLXBXEX/API/

contains three further microcode databases: `S1_4.PDB`, `S1_8.PDB`, and `S1_9.PDB` which together contain 0x630, 0x632, 0x633, 0x634, 0x650, 0x651, all with genuine looking dates from 1996/1997/1998:

```
$ for pdb in updates/PEP1.PDB ./*.PDB ; do echo $pdb ; hexdump -C $pdb | cut -c5-58 ; done | grep -E '(PDB|^..00  01 00)'
./S1_4.PDB
0000  01 00 00 00 13 00 00 00  96 19 27 08 30 06 00 00
0800  01 00 00 00 20 00 00 00  96 19 03 09 32 06 00 00
1000  01 00 00 00 32 00 00 00  96 19 12 12 33 06 00 00
1800  01 00 00 00 33 00 00 00  97 19 16 06 34 06 00 00
./S1_8.PDB
0000  01 00 00 00 32 00 00 00  96 19 12 12 33 06 00 00
0800  01 00 00 00 33 00 00 00  97 19 16 06 34 06 00 00
1000  01 00 00 00 27 00 00 00  98 19 23 01 50 06 00 00
./S1_9.PDB
0000  01 00 00 00 32 00 00 00  96 19 12 12 33 06 00 00
0800  01 00 00 00 33 00 00 00  97 19 16 06 34 06 00 00
1000  01 00 00 00 27 00 00 00  98 19 23 01 50 06 00 00
1800  01 00 00 00 29 00 00 00  98 19 23 01 51 06 00 00
```

**Comment by sladen** [comment]
An even older version of the BIOS updater (`v1.0f`, July 1996) exists at:
* http://www.elhvb.com/mobokive/Archive/A-trend/bios/BIOS_flash%20tools/bup_util.exe

This contains the same `PEP1.PDB` with 0x612, 0x616, 0x617, but an older version of the executable called simply `CHECKUP.EXE`.

However, far more interesting is diffing the `CHECKUP.HLP` readme text file.  This shows that between July 1996 and September 1996 the terminology *Stepping data file* was changed to *BIOS Update database*; for example:
* `Specify stepping data file [current: pep.pdb]`
* `ERROR: Update not loaded. All stepping data slots are occupied`
* `ERROR: BIOS does not contain sufficient number of slots to store the stepping data update(s).`
* `ERROR: Update not loaded. Stepping data was rejected`

**Comment by platomav** [comment]
Hello,

You can load these files into MC Extractor and it will automatically let you know if something is not found in the full DB. In this case, all the aforementioned files have already known microcodes. MC Extractor also [knows about the typo made in 1996](https://github.com/platomav/MCExtractor/blob/ed264fec5ece43c2a7d2e536a62ca9167a20017c/MCE.py#L1135) and ignores it automatically. Intel did release a new microcode which had the typo fixed shortly after. As for the text diff, it is a matter of terminology. They probably initially build these files to update the different steppings of the same processor but then expanded them for multiple CPUIDs or similar.

**Comment by sladen** [comment]
The three `0xC5` microcode updates from `PEP1.PDB` would appear to be 11-months earlier (January 1996) than anything in the database (December 1996, and `0xC6`).

(These January 1996 dates much more closely correspond to the February 1996 date of `v1.0f`.)

**Comment by sladen** [comment]
@platomav is the a reason for not wishing to add these three very-early Pentium Pro version 0xc5 microcode updates?

**Comment by platomav** [comment]
Did you read my earlier reply? They are already in [MC Extractor](https://github.com/platomav/MCExtractor) DB. If you are talking about this repo, only the latest are kept here as explained at the 2nd bullet point.

**Comment by sladen** [comment]
Might it be worth updating the text:

* "The Intel, AMD & VIA CPU Microcode Repositories is a collection of every Intel, AMD & VIA CPU Microcodes we have found."

to more closely reflect that the "Microcode Repositories" only includes the latest microcode version?

**Comment by platomav** [comment]
It's at the 2nd bullet in bold text:

> Every microcode has an **Update Revision** which is increased when fixes are applied. For example, 0x00000A0B < 0x00000A0E. **Only the latest microcodes of each CPUID are included in the repositories.**

**Comment by sladen** [comment]
Indeed, but after the sentences:

* "This is a collection of every Production Intel, AMD and VIA CPU microcode we have found."
* "Collecting all available CPU microcodes …"

**Comment by JacobWKlein** [comment]
platomav:
The person's request is valid.

The first sentence says:
This is a collection of every Production Intel, AMD and VIA CPU microcode we have found.
... which isn't true.

Another sentence says:
Collecting all available CPU microcodes is important for upgrading/downgrading purposes
... but you don't collect them all, and also downgrading is kind of impossible if you only provide the latest versions.

It'd be better to be clearer, to say that you keep the latest versions only, and that the repository history contains some but not all previous versions.

**Comment by platomav** [comment]
Done

**Comment by JacobWKlein** [comment]
> 
> 
> Done

Looks much better to me. Thank you.

**Comment by sladen** [comment]
Yes, it is better that the documentation reflects reality.  Thank you.

What made this particular project notable and different was (according to the documentation) a stated goal to produce a complete library of microcode, and maintain that collection under revision control.  With that stated goal of collating everything removed, the documentation now makes the project appear much more similar to other partial collections of microcode.

Would it make sense to maintain a second branch that did indeed contain *everything*.  This could be used in the longer term for researchers, archaeologists, those needing to down-grade and other use-cases?

**Comment by platomav** [comment]
There are no other projects or official sources out there like this one, otherwise it wouldn't exist. Initially the plan was to have all microcodes here (thus the readme) but I decided to stick to the latest just in case Intel doesn't like the redistribution of insecure or known non-supported features enabling micrcodes. I doubt that AMD and especially VIA would care but I can't say the same about Intel.

**Comment by ValZapod** [comment]
> in case Intel doesn't like the redistribution of insecure or known non-supported features enabling micrcodes

But we do have all microcodes here, you will just need to go to history of commits. And git clone && git checkout will do the thing. Just saying.
