### ISSUE TITLE
Missing microcodes from HM55 chipset

### ISSUE THREAD

**Issue by FPSUsername** [platomav/CPUMicrocodes#13]
It seems that my old laptop has some microcodes not available in this repository. MCExtractor flags some of them as outdated.

![HM55](https://user-images.githubusercontent.com/10143926/54834233-0c947b00-4cc0-11e9-8ed2-c6068c120268.png)

[Intel.zip](https://github.com/platomav/CPUMicrocodes/files/2997160/Intel.zip)

**Comment by platomav** [comment]
The github microcode repository includes the **Latest Production (PRD)** microcodes so that's normal.

**Comment by FPSUsername** [comment]
The ones missing are not PRD?

**Comment by platomav** [comment]
Check your **Type** field at your picture

**Comment by FPSUsername** [comment]
Oh, didn't notice that. Thanks!

**Comment by platomav** [comment]
No problem, closing this one. ;)
