### ISSUE TITLE
patches cannot be applied on AMD: amd-ucodegen is dead

### ISSUE THREAD

**Issue by owlshrimp** [platomav/CPUMicrocodes#14]
Hi,

It looks like github.com/groeck/amd-ucodegen is dead, meaning that the AMD files located here cannot be converted into the correct AMD container format for loading by linux.

It appears no mirrors of this tool exist, meaning that the microcode files here for AMD cannot be used.

-Matt

**Comment by platomav** [comment]
This is not related to this repo as its goal is to provide the raw microcode updates. How these are used or applied by end-users is up to them. All microcodes can be used by inserting them into the BIOS for example.

**Comment by Matthew-Bradley** [comment]
Should have searched github instead of searching google.
This looks like a mirror https://github.com/AndyLavr/amd-ucodegen

**Comment by akostadinov** [comment]
Thank you for the pointer. I was also struggling to find a way to install this binary.

The project is present now at https://github.com/AndyLavr/amd-ucodegen

I managed to deploy successfully in this way. FYI here's my blog about the whole process as it was way less clear than I expected.

https://rboci.blogspot.com/2024/04/zenbleed-microcode-update-on-amd-ryzen.html
