### ISSUE TITLE
new microcode: !New_cpu206D6_plat6D_ver0000061F_2019-05-21_PRD_990D3CF1.bin

### ISSUE THREAD

**Issue by lilyanatia** [platomav/CPUMicrocodes#15]
new microcode 61F for 206D6:

https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/blob/master/intel-ucode/06-2d-06

**Comment by platomav** [comment]
Thank you very much for letting me know. Please report any microcodes which are missing from the [MC Extractor](https://github.com/platomav/MCExtractor) database at the [CPU Microcode Repositories Discussion Topic](https://www.win-raid.com/t3355f47-Intel-AMD-amp-VIA-CPU-Microcode-Repositories.html). I'll update the README with this note as well at the next commit.
