### ISSUE TITLE
Are some of these new?

### ISSUE THREAD

**Issue by KedarWolf** [platomav/CPUMicrocodes#16]
Quite a few new Intel MCs in Windows 10 build 18963:
!New_cpu306F4_plat80_ver00000016_2019-06-17_PRD_0FAB37D5.bin
!New_cpu40671_plat22_ver00000021_2019-06-13_PRD_B772C835.bin
!New_cpu406F1_platEF_ver0B000038_2019-06-18_PRD_E705E458.bin
!New_cpu50654_platB7_ver02000064_2019-07-31_PRD_8E7C22B2.bin
!New_cpu50662_plat10_ver0000001C_2019-06-17_PRD_6A540EAF.bin
!New_cpu50663_plat10_ver07000019_2019-06-17_PRD_C5E77EC6.bin
!New_cpu50664_plat10_ver0F000017_2019-06-17_PRD_43C2AD6B.bin
!New_cpu50665_plat10_ver0E00000F_2019-06-17_PRD_5E04DBCA.bin
!New_cpu806E9_plat10_ver000000BA_2019-04-30_PRD_D3A29416.bin
!New_cpu806E9_platC0_ver000000BA_2019-04-30_PRD_C93F17A1.bin
!New_cpu806EA_platC0_ver000000BA_2019-04-30_PRD_EF86C437.bin
!New_cpu906E9_plat2A_ver000000BA_2019-04-30_PRD_19E2FDAE.bin
!New_cpu906EA_plat22_ver000000BA_2019-04-30_PRD_4BEBC386.bin
!New_cpu906EB_plat02_ver000000BA_2019-04-30_PRD_D690DE6C.bin

**Comment by KedarWolf** [comment]
Now sure how to attach a .zip file with the micro-codes, but I have them.

https://www.win-raid.com/file.php?url=http%3A%2F%2Ffiles.homepagemodules.de%2Fb602300%2Ff47t3355p85254n2_asQDXWuq.zip&r=&content=RE%3A_Intel%2C_AMD_%26amp%3B_VIA_CPU_Microcode_Repositories_Discussion from WinRaid forums.

**Comment by platomav** [comment]
Indeed quite a lot. Thank you.

Please prefer the Win-Raid discussion thread to report microcodes not in the DB. I'll close this issue now.
