### ISSUE TITLE
What is the next of 206A7 ?

### ISSUE THREAD

**Issue by Azaretdodo** [platomav/CPUMicrocodes#17]
Hello,

What is the next of 206A7 ?
![CPUNow](https://user-images.githubusercontent.com/30596513/68069542-8239ec80-fd61-11e9-8048-c7c552d1e26a.jpg)

Thank you in advance to asnwer my question,

Regards.

Azaretdodo.

**Comment by platomav** [comment]
I don't think that question makes sense. The direct answer is that the "next" of 206A7 is 206A8 but such a CPU stepping never existed. Please use the [forum discussion thread](https://www.win-raid.com/t3355f47-Intel-AMD-VIA-amp-Freescale-CPU-Microcode-Repositories-Discussion.html) for such hypothetical/off-topic or similar questions. If someone wants to reply there, I'm sure they will.

**Comment by Azaretdodo** [comment]
Just one question about the Forum

If anybody answer I receive an e-mail ?

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________
