### ISSUE TITLE
What is the format of the files in the repository?

### ISSUE THREAD

**Issue by owlshrimp** [platomav/CPUMicrocodes#19]
Hello,

What is the format of the files in the repository?

Are they raw binaries from BIOSs?
Are they MC Extractor Microcode Blobs? (MCB)
Are they in the correct format to be loaded by linux? (ie microcode_amd_fam16h.bin)

How can they be prepared for loading by linux?

-Matt

**Comment by platomav** [comment]
They are raw microcode blobs as they are given from Intel/AMD/VIA/FSL to OEMs and as they are included in the BIOS.

To load them by Linux or similar, you'll have to search online. Only the raw microcode binaries are included in this repo.
