### ISSUE TITLE
Source for current Intel microcode updates?

### ISSUE THREAD

**Issue by merge** [platomav/CPUMicrocodes#2]
Currently Intel is slowly filling up it's [pdf](https://newsroom.intel.com/wp-content/uploads/sites/11/2018/03/microcode-update-guidance.pdf) with updates marked as "Production" ready.

* Is there any indication that Intel will do a "Linux microcode package" someday soon?
* Besides waiting for a random vendor BIOS update with said updated version integrated for one specific CPU model family, and analyzing and trying to extract the microcode out of it, which would take ages, if at all possible for all models, what else can we do to get them?

**Comment by platomav** [comment]
* It makes sense for them to do so but I'm not privy to such info.
* Scanning OEM BIOS has always been the best method to get them. Intel microcodes can be found at OEM BIOS (often updated, usually latest), at Windows/Linux libraries (rarely updated, some outdated) or at their own download site (not often updated, some outdated). They are not given to end-users directly.
