### ISSUE TITLE
Microcodes listed, but missing

### ISSUE THREAD

**Issue by PetrBorodkin** [platomav/CPUMicrocodes#20]
Hello!
The following microcodes:
AMD cpu00830F10_ver08301005_2019-02-26_500DBEB3
AMD cpu00830F00_ver08300023_2019-02-25_AC6EF5B7
AMD cpu00830F10_ver08301002_2019-01-11_EB1F9E45
AMD cpu00830F00_ver0830000B_2018-12-07_EEFCCF1B
are listed inside r157.
Unfortunately, I was unable to find them here: https://github.com/platomav/CPUMicrocodes/commits/master/AMD
Could you please update the repository.
Best regards,
Petr Borodkin.

**Comment by platomav** [comment]
As explained in the README, only the **Latest** microcodes are present in the repository. The ones you list are old. You may be able to find them at old commits though.
