### ISSUE TITLE
Where do you get those from?

### ISSUE THREAD

**Issue by Axilot** [platomav/CPUMicrocodes#21]
Hello, this issue thread may be misleading and i am sorry for that. But just out of curiosity i am wondering where you get all of those microcodes from. I found the microcodes from Intel already in their github repository. The ones from AMD i could not find. I could find them however in the linux firmware. I hope you could help me answer that question. Thanks :D

**Comment by platomav** [comment]
https://github.com/platomav/CPUMicrocodes/blob/master/README.md > Disclaimer

**Comment by jaredmo** [comment]
@platomav Apologies if this has been addressed. Is there a good method to verify that these came from official sources (ex. hash, signature file, etc)? Specifically AMD family 19h.

This looks like an incredible amount of work for one person!
