### ISSUE TITLE
[REQUEST]: Missing one microcode for CPU 1067a?

### ISSUE THREAD

**Issue by ghost** [platomav/CPUMicrocodes#24]
Hi @platomav 

Currently the microcode for cpu 1067a is available for platforms 44 and B1. Would you be able to add one for platform 80 please?

Thanks!

Regards,
RG.

**Comment by ghost** [comment]
I might be mistaken about the platform. My demesg shows `microcode: sig=0x1067a, pf=0x80, revision=0x0`. It means platform 80 right?

**Comment by platomav** [comment]
Check the README > Field descriptions > PlatformID to find the right 1067A microcode for your Platform ID, which should be 0 (0x80 = b10000000 = 0).

**Comment by ghost** [comment]
@platomav Thanks so much!

Btw, in the intel repo, the latest microcode revision for CPU 1067a is a0b.  How come there is aoe here?
