### ISSUE TITLE
Downgrading microcode that disabled undervolting

### ISSUE THREAD

**Issue by aggillator** [platomav/CPUMicrocodes#25]
Hi there,

I wanted to know if downgrading to a prior microcode before intel blocked undervolting would re-enable it.  I've tried downgrading my BIOS but manufacturer (HP) has blocked downgrading.  Thanks in advance for any help and guidance.

Adam

**Comment by platomav** [comment]
This is not an issue. You should ask at BIOS-related forums/communities (e.g. bios-mods, mydigitallife, win-raid etc.) to help you out.
