### ISSUE TITLE
no new code available for my intel i5 5200U

### ISSUE THREAD

**Issue by Azaretdodo** [platomav/CPUMicrocodes#26]
Hello,

No new code available for my setup core i5 5200U : 

The InSpectre window
![image](https://user-images.githubusercontent.com/30596513/164886798-ab3a6ec0-7484-43a7-93c6-06af77471cb9.png)

The folder Intel
![image](https://user-images.githubusercontent.com/30596513/164886818-f5ff8672-f2ef-4441-a39b-9608af36f373.png)

Thank you in advance for your soon work,

Regards.

Azaretdodo.

**Comment by platomav** [comment]
That CPUID does exist. Make sure you download the repo correctly, that you use Windows search correctly etc.

**Comment by Azaretdodo** [comment]
This doesn't exist I understand how to search,

Stop lies,

Regards.


Dorian Rosse.
________________________________

**Comment by Azaretdodo** [comment]
You say does exist or exist ?

Thanks you in advance for your answer,

Regards.


Dorian Rosse.
________________________________

**Comment by Harvester57** [comment]
Like it was said previously, you should learn how to search the repository: https://github.com/platomav/CPUMicrocodes/blob/master/Intel/cpu306D4_platC0_ver0000002F_2019-11-12_PRD_8B6D899D.bin

**Comment by Azaretdodo** [comment]
Thanks you because this should be thus my system seems bad work,

Regards.


Dorian Rosse.
________________________________
