### ISSUE TITLE
cpu50654_plat97 Microcode needed for intel core i9-7900X

### ISSUE THREAD

**Issue by brichan** [platomav/CPUMicrocodes#27]
Intel Core i9-7900X (Skylake-X/Stepping U0/SSPEC SR3L2)

The Microcode for this CPU is indeed cpu50654_platB7, but if cpu50654_plat97 is also not present in the BIOS, the CPU will not be recognized in the UEFI BIOS and the Microcode will not be updated.
My MB is AsRock X299 Steel Legend, but when I check the contents of X299 BIOS of ASUS ROG series, CPU Microcode Plat97 and PlatB7 are always present, and it does not seem to work without both.

I would like to see cpu50654_plat97 added to CPUMicrocodes as well.

**Comment by platomav** [comment]
Platform B7 replaces 97 and there is no official reason for both to exist. Intel is also offering the latest B7 for that CPUID [here](https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/tree/main/intel-ucode) (06-55-04), as expected. These motherboards may be doing that to support unofficial features or other tricks, but that is out of scope for this repository.
