### ISSUE TITLE
README suggestion: info on where to find the CPU id

### ISSUE THREAD

**Issue by ell1e** [platomav/CPUMicrocodes#29]
I sincerely apologize if this is the wrong place, but I wanted to suggest you add in more concrete info about how to assemble the CPU ID value. I assume it's based on the `/proc/cpuinfo` output which for this AMD Ryzen 5 5560U seems to list cpu family 25, model 80, stepping 0, and some cpu id level 16, whatever that means, but e.g. it doesn't seem quite obvious to me if these values need to be converted to hex first, which exact order they go, etc. Maybe at the very bottom of the README, it might be worth having a short example on how to assemble this for AMD CPUs? Sorry again if this isn't the place to suggest this.

**Comment by Harvester57** [comment]
You can use the CPUID identification tool from here: https://www.cpu-world.com/Download/CPU_identification.html

This will open up a HTML page with the decoded informations, for example:

![image](https://github.com/platomav/CPUMicrocodes/assets/7060295/652db0c3-d9e7-431f-b799-f52c47eff540)

**Comment by ell1e** [comment]
Coincidentally I just e-mailed cpu-world.com to ask whether there's a Linux version, but there doesn't seem to be! Linux's `cpuid` doesn't seem to output the info in the required format either.

**Comment by alexdelorenzo** [comment]
> Coincidentally I just e-mailed cpu-world.com to ask whether there's a Linux version, but there doesn't seem to be! Linux's `cpuid` doesn't seem to output the info in the required format either.

`CWID.exe` works under Wine :)

**Comment by ell1e** [comment]
Ah, very cool! Thank you so much, I just tested it and it does!

Maybe slightly related and since I haven't found a good different place to ask this (including AMD themselves, their support didn't seem to understand the question), do you know if there's any vague info available on how long after a CPU's release AMD might commonly produce such microcode updates for security issues? It seems to be 7 years for Intel, but for AMD I found no info. Of course I understand whatever you surmise on this would be completely non-binding anyway, but you seem like the type of person who might know.

**Comment by SkewedZeppelin** [comment]
bash one-liner
```
cpuid | grep "processor serial number =" | head -n1 | sed 's/.* = //;s/-0000.*//;s/-//'
```

**Comment by ell1e** [comment]
If anyone knows any vague info on how long AMD usually patches CPUs, I still haven't been able to find any info on this anywhere which is a little unsettling.
