### ISSUE TITLE
help for customize bios

### ISSUE THREAD

**Issue by Dexter83** [platomav/CPUMicrocodes#3]
Hello, I noticed that there is very little material on how to customize bios with updated microcodes, could you explain how to do it or give me some advice?
The checksum of the bios that personalize with the microcode is always wrong as ever?

**Comment by platomav** [comment]
This is a repository of CPU microcodes, not a guide on how to customize and/or update BIOS. I have thus closed this issue. You can read some good threads and possibly ask your questions at win-raid.com forum.
