### ISSUE TITLE
[Feature] Add links to binary source

### ISSUE THREAD

**Issue by jaredmo** [platomav/CPUMicrocodes#30]
I am trying to determine the original source for `cpu00A50F00_ver0A50000F_2023-07-07_72B4B8C6` so I can verify. I found [this post](https://winraid.level1techs.com/t/intel-amd-via-freescale-cpu-microcode-repositories-discussion/32301/959?u=phonemic) which I assume is the source. However, there is no link to where the original poster extracted the microcode.

It would be helpful to note sources here if that is possible. Thanks for the consideration!

**Comment by platomav** [comment]
Answered at https://winraid.level1techs.com/t/intel-amd-via-freescale-cpu-microcode-repositories-discussion/32301/1012?u=plutomaniac
