### ISSUE TITLE
cpu50656_platBF_ver04003605_2023-07-28_PRD_C0E56E3E.bin new one present!

### ISSUE THREAD

**Issue by karakarga07** [platomav/CPUMicrocodes#31]
At, https://www.intel.com/content/www/us/en/developer/topic-technology/software-security-guidance/processors-affected-consolidated-product-cpu-model.html

Instead of [cpu50656_platBF_ver04003605_2023-07-28_PRD_C0E56E3E.bin]

There is newer, "06_55H | 6 | NA | Cascade Lake Server9 | 2nd Generation Intel® Xeon® Scalable processor family | Server | 50656 | 04003006"

But I don´t know from where to download this microcode.

**Maybe I made a mistake, maybe not please check the links!**

They have dropped the revision number from 04003605 to 04003006 somehow?

**Comment by platomav** [comment]
I don't know, maybe they made a typo, you could try asking Intel about that version at https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files
