### ISSUE TITLE
New microcode for B06E0 plat01, version 10

### ISSUE THREAD

**Issue by Halo-Michael** [platomav/CPUMicrocodes#32]
[cpuB06E0_plat01_ver00000010_2022-12-19_PRD_2AA085DD.zip](https://github.com/platomav/CPUMicrocodes/files/14607209/cpuB06E0_plat01_ver00000010_2022-12-19_PRD_2AA085DD.zip)
I know it's already an newer version 15 here, but that's for plat11. It's newer than database MCExtractor r289‘s change.

**Comment by platomav** [comment]
That is an old microcode, already present at MCE DB and deprecated/superseded by the cpuB06E0_plat11 blob found here. Please read the section of the README about Intel Platform and how it works (01 = 0, 11 = 0,4):

https://github.com/platomav/CPUMicrocodes?tab=readme-ov-file#field-descriptions
