### ISSUE TITLE
AMD microcodes also need CPU equivalence table

### ISSUE THREAD

**Issue by maciejsszmigiero** [platomav/CPUMicrocodes#4]
First, many thanks for this repository! - before browsing through it I didn't realize that AMD-released microcode files in official linux-firmware repository don't actually contain the newest microcode
versions, even for their older CPUs.

However, for AMD microcodes the raw file and its CPUID is sometimes not enough.
One also needs so-called CPU equivalence table (see struct equiv_cpu_entry in arch/x86/include/asm/microcode_amd.h).
Such equivalence table tells that, for example, cpu00100F22 file is also valid for CPUID 00100F23
(that's a real example).

I don't know if the files that these updates are extracted from contain such equivalence tables,
but if they do they should be included in this repository (maybe just the latest version of them).

**Comment by platomav** [comment]
Thank you for your kind words. I am aware that AMD tends to show a different CPUID once the CPU has initialized. That's just one of the many things they do wrong and cause confusion. I've never seen such a CPU Equivalence Table but if there is, it's probably community driven. Either way, this is a microcode repository so it's up to the end-users to figure out how and what to update. The best thing to do is to update the microcodes inside the BIOS, which has the same CPUID as shown at the microcode header and thus in this repo.

**Comment by maciejsszmigiero** [comment]
Last AMD-released microcodes for Linux and Solaris (available here: https://web.archive.org/web/20160726141516/http://www.amd64.org/microcode.html ) are already released in a container file that includes such CPU equivalence table.

According to this paper: https://www.dcddcc.com/docs/2014_paper_microcode.pdf (page 5):
> [this table] eliminates duplicate microcode updates used by multiple processors from the same
> microarchitecture but with different processor signatures

So it is probably an optimization to avoid repeating the same microcode in a microcode container file.

If BIOSes don't carry such tables because at CPU power-up time the CPUIDs are unique we (Linux and Solaris users) will probably have to use the ones from the officially released container files.
So this issue can be closed then.
