### ISSUE TITLE
Donate Button is missing!

### ISSUE THREAD

**Issue by derjohn** [platomav/CPUMicrocodes#5]
Hey,
I think I owe you some beers or so for that great job! Where is the send beer button? :-)

rgds,
j

**Comment by platomav** [comment]
Hello derjohn,

Thank you for your inclination to donate. You can find a donate button at my [MC Extractor](https://github.com/platomav/MCExtractor/blob/master/README.md) project.

**Comment by platomav** [comment]
Thank you very much @derjohn. I'll go ahead and close this issue now. 😃
